project:
  type: website
  output-dir: docs

website:
  
  navbar:
    logo: images/crscph_logo.png
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Services
        href: services.qmd
      - text: Contact
        href: contact.qmd
      - text: Publications
        href: publications.qmd
      - text: Staff
        href: staff.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual
