project:
  type: website
  output-dir: docs

website:
  title: "CRSC-PH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services
      - href: contact.qmd
        text: Contact
      - href: publications.qmd
        text: publications

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: false

editor: visual


